# Generated by Django 4.2.6 on 2023-10-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_alter_course_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Person'},
        ),
    ]
